# -*- coding: utf-8 -*-
"""travel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15KbzjJaiq5D-LaQjol7W9nBmDWMKyHIc
"""

!pip install streamlit
import streamlit as st
import google.generativeai as genai

api_key="AIzaSyAe7VuGljvINRMj_98plhdLtUJG-J5jg9M"
genai.configure(api_key=api_key)
model_name= "gemini-1.5-pro",
def generate_itinerary(destination, days, nights):
    generation_config = {
       "temperature":0.4,
       "top_p":0.95,
        "max_output_tokens": 8192,
        "response_mime_type": "text/plain",
    }
    model = genai.GenerativeModel(
        model_name="gemini-1.5-pro",
        generation_config=generation_config)
    chat_session=model.start_chat(
        history=[
            {
                "role": "user",
                "parts":[f"write me a travel itinerary for {destination} for {days} days and {nights} nights,"
                ],
            },
        ]
    )

    response=chat_session.send_message(f"create a detailed travel itinerary for{days} days and {nights} nights in {destination}.")
    return response.text

st.title("Travel Itinerary Generator")
destination = st.text_input("Enter your desired destination:")
days = st.number_input("Enter the number of days:", min_value=1)
nights = st.number_input("Enter the number of nights:", min_value=0)


if st.button("Generate Itinerary"):
    if destination.strip() and days and nights >= 0:
        try:
            itinerary = generate_itinerary(destination, days, nights)
            st.text_area("Generated Itinerary:", value=itinerary, height=300)
        except Exception as e:
            st.error(f"An error occurred: {e}")
    else:
        st.error("Please make sure all inputs are provided and valid.")

"""First, I'll save the Streamlit application code into a file named `app.py`."""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import google.generativeai as genai
# 
# api_key="AIzaSyAe7VuGljvINRMj_98plhdLtUJG-J5jg9M"
# genai.configure(api_key=api_key)
# model_name="gemini-2.5-flash",
# def generate_itinerary(destination, days, nights):
#     generation_config = {
#        "temperature":0.4,
#        "top_p":0.95,
#         "max_output_tokens": 8192,
#         "response_mime_type": "text/plain",
#     }
#     model = genai.GenerativeModel(
#         model_name="gemini-2.5-flash",
#         generation_config=generation_config)
#     chat_session=model.start_chat(
#         history=[
#             {
#                 "role": "user",
#                 "parts":[f"write me a travel itinerary for {destination} for {days} days and {nights} nights,"
#                 ],
#             },
#         ]
#     )
# 
#     response=chat_session.send_message(f"create a detailed travel itinerary for{days} days and {nights} nights in {destination}.")
#     return response.text
# 
# st.title("Travel Itinerary Generator")
# destination = st.text_input("Enter your desired destination:")
# days = st.number_input("Enter the number of days:", min_value=1)
# nights = st.number_input("Enter the number of nights:", min_value=0)
# 
# 
# if st.button("Generate Itinerary"):
#     if destination.strip() and days and nights >= 0:
#         try:
#             itinerary = generate_itinerary(destination, days, nights)
#             st.text_area("Generated Itinerary:", value=itinerary, height=300)
#         except Exception as e:
#             st.error(f"An error occurred: {e}")
#     else:
#         st.error("Please make sure all inputs are provided and valid.")

"""Next, I'll install `pyngrok` to create a secure tunnel to expose the Streamlit app."""

!pip install pyngrok

"""Finally, I'll launch the Streamlit app and expose it using `ngrok`. You will need to obtain an `NGROK_AUTH_TOKEN` from your ngrok dashboard (https://dashboard.ngrok.com/get-started/your-authtoken) and add it to Colab's secrets manager (under the '🔑' icon on the left panel) as `NGROK_AUTH_TOKEN`."""

from pyngrok import ngrok
import subprocess
import os
from google.colab import userdata

# Terminate any existing ngrok tunnels
ngrok.kill()

# Get ngrok auth token from Colab secrets
NGROK_AUTH_TOKEN = userdata.get('NGROK_AUTH_TOKEN')
if not NGROK_AUTH_TOKEN:
    print("Please add your NGROK_AUTH_TOKEN to Colab Secrets.")
else:
    ngrok.set_auth_token(NGROK_AUTH_TOKEN)

    # Run Streamlit in the background
    # The port 8501 is the default port for Streamlit apps
    print("Starting Streamlit app...")
    # Use nohup to run streamlit in background and redirect output to a file
    # This prevents the process from being killed when the cell finishes execution
    subprocess.Popen(['nohup', 'streamlit', 'run', 'app.py', '--server.port', '8501', '&'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    # Create a public URL with ngrok
    try:
        # Give Streamlit a moment to start
        import time
        time.sleep(5)

        public_url = ngrok.connect(addr="8501", proto="http")
        print(f"Streamlit App URL: {public_url}")
    except Exception as e:
        print(f"Error creating ngrok tunnel: {e}")
        print("Please ensure you have set your NGROK_AUTH_TOKEN in Colab Secrets.")





from pyngrok import ngrok
import subprocess
import os
from google.colab import userdata

# Terminate any existing ngrok tunnels
ngrok.kill()

# Get ngrok auth token from Colab secrets
NGROK_AUTH_TOKEN = userdata.get('NGROK_AUTH_TOKEN')
if not NGROK_AUTH_TOKEN:
    print("Please add your NGROK_AUTH_TOKEN to Colab Secrets.")
else:
    ngrok.set_auth_token(NGROK_AUTH_TOKEN)

    # Run Streamlit in the background
    # The port 8501 is the default port for Streamlit apps
    print("Starting Streamlit app...")
    # Use nohup to run streamlit in background and redirect output to a file
    # This prevents the process from being killed when the cell finishes execution
    subprocess.Popen(['nohup', 'streamlit', 'run', 'app.py', '--server.port', '8501', '&'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    # Create a public URL with ngrok
    try:
        # Give Streamlit a moment to start
        import time
        time.sleep(5)

        public_url = ngrok.connect(addr="8501", proto="http")
        print(f"Streamlit App URL: {public_url}")
    except Exception as e:
        print(f"Error creating ngrok tunnel: {e}")
        print("Please ensure you have set your NGROK_AUTH_TOKEN in Colab Secrets.")

import google.generativeai as genai

api_key="AIzaSyDuUn3wC_9b2KN8ygcOEkITOiPa28KUMv4" # Use your actual API key
genai.configure(api_key=api_key)

for m in genai.list_models():
    if "generateContent" in m.supported_generation_methods:
        print(m.name)

from pyngrok import ngrok
import subprocess
import os
from google.colab import userdata

# Terminate any existing ngrok tunnels
ngrok.kill()

# Get ngrok auth token from Colab secrets
NGROK_AUTH_TOKEN = userdata.get('NGROK_AUTH_TOKEN')
if not NGROK_AUTH_TOKEN:
    print("Please add your NGROK_AUTH_TOKEN to Colab Secrets.")
else:
    ngrok.set_auth_token(NGROK_AUTH_TOKEN)

    # Run Streamlit in the background
    # The port 8501 is the default port for Streamlit apps
    print("Starting Streamlit app...")
    # Use nohup to run streamlit in background and redirect output to a file
    # This prevents the process from being killed when the cell finishes execution
    subprocess.Popen(['nohup', 'streamlit', 'run', 'app.py', '--server.port', '8501', '&'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    # Create a public URL with ngrok
    try:
        # Give Streamlit a moment to start
        import time
        time.sleep(5)

        public_url = ngrok.connect(addr="8501", proto="http")
        print(f"Streamlit App URL: {public_url}")
    except Exception as e:
        print(f"Error creating ngrok tunnel: {e}")
        print("Please ensure you have set your NGROK_AUTH_TOKEN in Colab Secrets.")